### PR TITLE
reach Puppet v4 compatibility

### PR DESCRIPTION
**Pull request by Phil-Friderici**
<b>don't merge</b> there is more work to do.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
Todo
```require => [ File['httpd_vdir'],```

needs to be changed to
```require => [ File['/etc/httpd/conf.d'],``` for Redhat
```require => [ File['/etc/apache2/sites-available'],``` for Debian

**Comment by ghoneycutt** [comment]
Can we close this in lieu of your recent PR for puppetv4 support?

**Comment by Phil-Friderici** [comment]
@ghoneycutt sorry I did not quite understand. Which other PR ?

Support for Puppet v4 is a quite complex scenario for this module because of the needed submodules.
At the moment not all of them are Puppet v4 aware.
Also because Puppet v4 doesn't support Passenger.

Maybe it makes more sense to create a puppet-module-puppet4 fork instead ?

**Comment by Phil-Friderici** [comment]
closing as v2.19.0 (https://github.com/ghoneycutt/puppet-module-puppet/commit/6dbd7ee6d58b2b8ab04976ee2332c82cf92fa540) added support for the client side

**Comment by ghoneycutt** [comment]
We could stop development on this, which is pretty much stopped anyhow and make the next major version puppet v4 only and drop support for apache/passenger/dashboard etc. You running Puppet v4 yet?

**Comment by Phil-Friderici** [comment]
Yes, we are preparing an update to Puppet 4.
For the server/client configuration we use these two modules:
https://github.com/jwennerberg/puppet-module-puppetserver
https://github.com/propyless/puppet-module-puppet

I am sure you can get some inspiration there.
As both authors have left us, it might be the case that we fork at a later time, we'll see.

**Pull request closed without merging**
