### PR TITLE
prepare for Puppet v4 compatibility

### PR DESCRIPTION
**Pull request by Phil-Friderici**
This is work in progress to get this module working on Puppet v4 and future parser.

<b>Don't merge yet</b>

### CODE REVIEW

**Comment by ghoneycutt** [comment]
I'm not sure this code will make sense with v4 since it is not using apache/passenger. Some of the maintenance might make sense as well as the client config.

**Comment by Phil-Friderici** [comment]
@ghoneycutt The remaining errors are all related to dependency modules as source. This will need some more research. Thanks for the hint that apache/passenger is not used with Puppet v4. Didn't thought about that....

**Comment by Phil-Friderici** [comment]
successfully tested mysql v3.6.0 (master) to be compatible

**Comment by Phil-Friderici** [comment]
closed in favor of https://github.com/ghoneycutt/puppet-module-puppet/pull/107

**Pull request closed without merging**
