### PR TITLE
Convert manual vhost config to use apache::vhost

### PR DESCRIPTION
**Pull request by emahags**
Took a shot at converting the module to use apache::vhost instead of manual configuration. Requires at least 0.11.0 of puppetlabs/puppetlabs-apache, tested with 1.1.1.

Hopefully this commit can be used, but it might require some more spec tests.

### CODE REVIEW

**Comment by emahags** [comment]
@ghoneycutt I have updated the pull request with some additional code. It has been run for a while in production, but it should probably be tested by someone else before it's merged.

**Comment by propyless** [comment]
Hello,
whats the current status for this PR?

**Comment by ghoneycutt** [comment]
I need to test it in my environment. Since it updates apache, which is a good thing, it has quite the impact on some other modules and I want to ensure that they are all working together as expected after merging this.

**Comment by propyless** [comment]
Ok! Ofcourse that sounds wise ,just wanted to make sure that this PR was still active! =)

**Comment by ghoneycutt** [comment]
I'm declaring bankruptcy on all issues and PR's against this module as I change it to adopt Puppet v4. The master branch will now track that and a legacy branch 'puppetv3' will exist for people still running Puppet v3. I appreciate your work and involvement and hope this ultimately gets us all in a better place with regards to managing our Puppet infrastructure.

**Pull request closed without merging**
