### PR TITLE
Improve spec tests for maintenance class

### PR DESCRIPTION
**Pull request by anders-larsson**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
I think you need to add osfamily and operatingsystemrelease to the facts hash for each test as the other tests have

**Comment by anders-larsson** [comment]
Hmm. Looking at the spec tests it seems to fail on other tests than those added by me which is weird. The tests aren't even in the same file. Looking into it

**Comment by ghoneycutt** [comment]
Running your code locally I do not see any errors. Hmm.

**Comment by anders-larsson** [comment]
Any suggestions? I've heard that @Phil-Friderici and @propyless had similar issues with other pull requests and travis.

**Comment by ghoneycutt** [comment]
I pushed your code to another branch, PR #96, to see if re-running travis helps. I'm at a loss here.

**Comment by Phil-Friderici** [comment]
Yes, travis is failing on builds that were good some days before. Don't know what's wrong at the moment

**Comment by Phil-Friderici** [comment]
For testing I did a nothing chaning commit and it failed :(
https://github.com/Ericsson/puppet-module-vas/pull/49

**Comment by ghoneycutt** [comment]
I'm working on a fix now

**Comment by Phil-Friderici** [comment]
@ghoneycutt good luck

**Pull request closed without merging**
